package com.base.project.mockdata

import com.base.project.domain.model.PixabayImageSource

class MockPixabayImageSource {
	companion object {
		val PIXABAY_IMAGE_SOURCE by lazy { getPixabayImageSource() }

		val PIXABAY_IMAGE_SOURCE_PREVIEW_URL = "PIXABAY_IMAGE_SOURCE_PREVIEW_URL"
		val PIXABAY_IMAGE_SOURCE_PREVIEW_HEIGHT = 10
		val PIXABAY_IMAGE_SOURCE_LIKES = 11
		val PIXABAY_IMAGE_SOURCE_FAVORITES = 12
		val PIXABAY_IMAGE_SOURCE_TAGS = "PIXABAY_IMAGE_SOURCE_TAGS"
		val PIXABAY_IMAGE_SOURCE_WEBFORMAT_HEIGHT = 13
		val PIXABAY_IMAGE_SOURCE_VIEWS = 14
		val PIXABAY_IMAGE_SOURCE_WEBFORMAT_WIDTH = 15
		val PIXABAY_IMAGE_SOURCE_PREVIEW_WIDTH = 16
		val PIXABAY_IMAGE_SOURCE_COMMENTS = 17
		val PIXABAY_IMAGE_SOURCE_DOWNLOADS = 18
		val PIXABAY_IMAGE_SOURCE_PAGE_URL = "PIXABAY_IMAGE_SOURCE_PAGE_URL"
		val PIXABAY_IMAGE_SOURCE_WEBFORMAT_URL = "PIXABAY_IMAGE_SOURCE_WEBFORMAT_URL"
		val PIXABAY_IMAGE_SOURCE_IMAGE_WIDTH = 19
		val PIXABAY_IMAGE_SOURCE_USER_ID = 20
		val PIXABAY_IMAGE_SOURCE_USER = "PIXABAY_IMAGE_SOURCE_USER"
		val PIXABAY_IMAGE_SOURCE_TYPE = "PIXABAY_IMAGE_SOURCE_TYPE"
		val PIXABAY_IMAGE_SOURCE_ID = 21
		val PIXABAY_IMAGE_SOURCE_USER_IMAGE_URL = "PIXABAY_IMAGE_SOURCE_USER_IMAGE_URL"
		val PIXABAY_IMAGE_SOURCE_IMAGE_HEIGHT = 22

		private fun  getPixabayImageSource(): PixabayImageSource {
			return PixabayImageSource(
				previewURL = PIXABAY_IMAGE_SOURCE_PREVIEW_URL,
				previewHeight = PIXABAY_IMAGE_SOURCE_PREVIEW_HEIGHT,
				likes = PIXABAY_IMAGE_SOURCE_LIKES,
				favorites = PIXABAY_IMAGE_SOURCE_FAVORITES,
				tags = PIXABAY_IMAGE_SOURCE_TAGS,
				webformatHeight = PIXABAY_IMAGE_SOURCE_WEBFORMAT_HEIGHT,
				views = PIXABAY_IMAGE_SOURCE_VIEWS,
				webformatWidth = PIXABAY_IMAGE_SOURCE_WEBFORMAT_WIDTH,
				previewWidth = PIXABAY_IMAGE_SOURCE_PREVIEW_WIDTH,
				comments = PIXABAY_IMAGE_SOURCE_COMMENTS,
				downloads = PIXABAY_IMAGE_SOURCE_DOWNLOADS,
				pageURL = PIXABAY_IMAGE_SOURCE_PAGE_URL,
				webformatURL = PIXABAY_IMAGE_SOURCE_WEBFORMAT_URL,
				imageWidth = PIXABAY_IMAGE_SOURCE_IMAGE_WIDTH,
				userId = PIXABAY_IMAGE_SOURCE_USER_ID,
				user = PIXABAY_IMAGE_SOURCE_USER,
				type = PIXABAY_IMAGE_SOURCE_TYPE,
				id = PIXABAY_IMAGE_SOURCE_ID,
				userImageURL = PIXABAY_IMAGE_SOURCE_USER_IMAGE_URL,
				imageHeight = PIXABAY_IMAGE_SOURCE_IMAGE_HEIGHT
			)
		}
	}
}